### ISSUE TITLE
`send_capacity` does not check the minimal required capacity of the change cell

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb-sdk-ruby#100]
For example, if I have only one 100 bytes cell, I want to send 60 bytes to someone else, there are only 40 bytes left for change, which is not enough to hold a cell.

**Comment by doitian** [comment]
The reason is that the const `MIN_CAPACITY` is not enough to hold a cell with secp256k1 lock. It should be fixed after #94 is correctly implemented.

**Comment by classicalliu** [comment]
#94 is fixed by #101
