### ISSUE TITLE
 Consecutive Transactions

### ISSUE THREAD

**Issue by NedValY** [nervosnetwork/ckb-sdk-ruby#125]
- The same tx_hash is generated when consecutive transactions occur
- When sending the same price to the same address continuously, the same tx_hash is generated.
- An error occurs if it is executed several times consecutively.
- It is not clear how much the cost of the attack will be because the fee value has not yet been set. However, it is expected that it will be helpful to prevent the attack and to develop the application by giving priority to the recovery of the continuous transaction.
This may be a daemon issue or a policy.

[60] pry(main)> send_txHash = sender_wallet.send_capacity(recv_wallet.address, 60 * 10 ** 8 )
=> "0x9f7fff7ce189c5693682eef48a7cf163824e7690c8917d4ff9ebfe0ec4ee0ef0"
[61] pry(main)> send_txHash = sender_wallet.send_capacity(recv_wallet.address, 60 * 10 ** 8 )
=> "0x9f7fff7ce189c5693682eef48a7cf163824e7690c8917d4ff9ebfe0ec4ee0ef0"
[62] pry(main)> send_txHash = sender_wallet.send_capacity(recv_wallet.address, 60 * 10 ** 8 )
=> "0x9f7fff7ce189c5693682eef48a7cf163824e7690c8917d4ff9ebfe0ec4ee0ef0"
[63] pry(main)> send_txHash = sender_wallet.send_capacity(recv_wallet.address, 60 * 10 ** 8 )
=> "0x9f7fff7ce189c5693682eef48a7cf163824e7690c8917d4ff9ebfe0ec4ee0ef0"
[64] pry(main)> send_txHash = sender_wallet.send_capacity(recv_wallet.address, 60 * 10 ** 8 )
CKB::RPCError: jsonrpc error: {:code=>-3, :message=>"UnresolvableTransaction(Dead(OutPoint { cell: Some(CellOutPoint { tx_hash: 0xa4bd28d6342a1e91bc2948d4bb34f40146e04efebda5a8107ec703e0a143e72c, index: 0 }), block_hash: Some(1c2a781b20c643dd0815446c67064647329425e337fdd35484a1c8e1904ad73f) }))"}

**Comment by classicalliu** [comment]
It always get the live cells from chain and order by block number and index, so if call `send_capacity` with same address and same capacity, it will generate same transaction if the previous one not committed to blockchain.

**Comment by classicalliu** [comment]
The `fee` of transaction is always `0` now, we'll consider to add this through your advice, thanks.
