### ISSUE TITLE
Extract address format/generation related info out of API class

### ISSUE THREAD

**Issue by ashchan** [nervosnetwork/ckb-sdk-ruby#18]
It doesn't fit in the `API` class.

For example: https://github.com/nervosnetwork/ckb-sdk-ruby/pull/13/files#diff-3d60bcb04ee87c3bba4b2cf253fc6db7R23 has `PREFIX_MAINNET` and `prefix` property which is totally scoped to address format, but not API module.

**Comment by classicalliu** [comment]
https://github.com/nervosnetwork/ckb-sdk-ruby/pull/26
