### ISSUE TITLE
How to new a script with more than one arg?

### ISSUE THREAD

**Issue by Focinfi** [nervosnetwork/ckb-sdk-ruby#220]
The [test code](https://github.com/nervosnetwork/ckb-sdk-ruby/blob/develop/spec/ckb/types/script_spec.rb#L40:L48) in spec seems like that the length of one arg must be 20B？ How to send args have different lengths?
```ruby
    it "should build correct hash when args more than one" do
      script = CKB::Types::Script.new(
        code_hash: code_hash,
        args: "0x3954acece65096bfa81258983ddb83915fc56bd83954acece65096bfa81258983ddb83915fc56bd8"
      )
      expect(
        script.compute_hash
      ).to eq api.compute_script_hash(script)
    end
  end
```

**Comment by shaojunda** [comment]
you can just combine multiple args into one `string`  if the `Script` needs it.

**Comment by Focinfi** [comment]
thanks
