### ISSUE TITLE
Check capacity is enough to hold output in `send_capacity`

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb-sdk-ruby#94]
We can add a guard in `send_capacity` to check whether the capacity is enough to hold the output, in this PR or a new PR.

_Originally posted by @doitian in https://github.com/nervosnetwork/ckb-sdk-ruby/pull/73#issuecomment-494877252_

**Comment by doitian** [comment]
Remove the hard-coded `MIN_CAPACITY` as well

**Comment by classicalliu** [comment]
https://github.com/nervosnetwork/ckb-sdk-ruby/pull/101
